version: "3.8"

volumes:
  mongo_data: 

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGODB_ROOT_ADMIN: admin
      MONGODB_ROOT_PASSWORD: pass
    volumes:
    - mongo_data:/data